version: "3.5"

services:
  mongo-express:
          env_file: ../config/.dockerenv
          image: ${MONGODBName}_mongo-express
          ports:
                  - "127.0.0.1:${MONGOexpressPort}:8081"
          build:
                  context: ./
                  dockerfile: ./Dockerfile
                  args:
                        ME_CONFIG_MONGODB_URL: $${ME_CONFIG_MONGODB_URL}
                        ME_CONFIG_MONGODB_ENABLE_ADMIN: $${ME_CONFIG_MONGODB_ENABLE_ADMIN}
                        ME_CONFIG_MONGODB_SSL: $${ME_CONFIG_MONGODB_SSL}
                        ME_CONFIG_SITE_COOKIESECRET: $${ME_CONFIG_SITE_COOKIESECRET}
                        ME_CONFIG_SITE_SESSIONSECRET: $${ME_CONFIG_SITE_SESSIONSECRET}
                        ME_CONFIG_BASICAUTH: $${ME_CONFIG_BASICAUTH}
                        ME_CONFIG_BASICAUTH_USERNAME: $${ME_CONFIG_BASICAUTH_USERNAME}
                        ME_CONFIG_BASICAUTH_PASSWORD: $${ME_CONFIG_BASICAUTH_PASSWORD}
                        MONGOexpressPort: $${MONGOexpressPort}
                        MONGODBName: $${MONGODBName}
